### ISSUE TITLE
Is it possible to list all files in the served directory?

### ISSUE THREAD

**Issue by olastor** [expressjs/serve-static#104]
I hope I am not abusing the issues tracker for my question, but I haven't found documentation about this anywhere.

I'd like to use this module for serving files which have a secure hash as filename and I don't want anybody else except those who know the name of the file to access it. Does this module support preventing to list the index of the public directory?

**Comment by dougwilson** [comment]
This module doesn't provide a way to get a directory listing, correct.

**Comment by olastor** [comment]
Ok, so my files are "safe" if nobody knows their name?

**Comment by dougwilson** [comment]
At least with this module. This module just takes the given URL and looks up the file on the file system by that name. If it exists it will be served up, otherwise next() will be called.

**Comment by olastor** [comment]
Ok, thanks for the quick response!
