### ISSUE TITLE
restify support

### ISSUE THREAD

**Issue by retrohacker** [expressjs/serve-static#106]
Heya!

I'm interested in using this module for restify, but restify differs from express in that it requires middleware always call `next`.

Is there a reliable way to determine whether or not `serve-static` has finished handling a request and will not be calling `next`?

If not, can I put in a feature request to add an option that forces `serve-static` to always call `next`, or to at least expose enough state to determine whether or not it has finished handling a request? I'm happy do the implementation if we can come up with a palatable API.

**Comment by retrohacker** [comment]
It looks like something along the lines of:

```js
var restify = require('restify');
var serveStatic = require('serve-static');

var app = restify.createServer();
var serve = serveStatic('./foo/bar');

app.get('.*', function(req, res, next) {
    serve(req, res, function() {
        res.end('', 404);
    });
    res.on('finish', function () {
        next();
    });
});

app.listen(8080);
```

Does the trick, but it's not very clean. I could provide a wrapper around this module that handles this for users.

**Comment by dougwilson** [comment]
Hi @retrohacker ! 

> I'm interested in using this module for restify, but restify differs from express in that it requires middleware always call next.

Weird, never through one would do that, and I believe that wasn't the case before. Maybe they changed in one of their major revisions.

> Is there a reliable way to determine whether or not serve-static has finished handling a request and will not be calling next?

If you combine the call with something like the `finish` event on `res` (https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_finish) I think so. This may or may not work, depending on which point in the lifecycle you're supposed to be calling `next()` on a handled response with Restify (untested):
```js
var serveStatic = require('serve-static')

function restifyServeStatic(options) {
  var middleware = serveStatic(options)
  return (req, res, next) {
    res.addListener('finish', next)
    middleware(req, res, function (err) {
      res.removeListener('finish', next)
      next(err)
    })
  }
}
```

> If not, can I put in a feature request to add an option that forces serve-static to always call next, or to at least expose enough state to determine whether or not it has finished handling a request? I'm happy do the implementation if we can come up with a palatable API.

I mean, I'm not sure if I'd really be super interested. In the end, this module is a pretty thin wrapper to make an Express-like middleware out of the `send` module. I would assume one could make the exact same thing for Restify: make a middleware that converts `send` to a Restify middleware? Maybe even make a module that converts _any_ Express-like middlewares into Restify middlewares?

**Comment by dougwilson** [comment]
I'd have to look into Restify, but there could be some more differences that may complicate really having two-in-one type of deal as well, for example how mounting works in Express (stripping prefixes and providing things like `req.originalUrl` -- not sure if Restify does this or not off-hand.

**Comment by retrohacker** [comment]
Hey @dougwilson :smile: thank you for the quick response :heart:

> Weird, never through one would do that, and I believe that wasn't the case before. Maybe they changed in one of their major revisions.

Restify considers a response lifecycle to be the entire middleware stack (including post-processing after a request has been sent). The stack is driven by the invocation of `next`, which results in a strict requirement to always call `next`.

The advantage is that this gives deep insight into the request/response cycle (we can track a request all the way through the middleware stack and then handle non-request stuff like reporting out metrics at the end without blocking the response), the trade-off is that not calling `next` leaves all the instrumentation in a limbo state waiting for the middleware to continue, which is a slow per-request memory leak. There might be a better way for us to tackle this in the restify framework (i.e. wiring up the post processing middleware to the `res.on('finish'` handler) but for now `next` is required.

>  Maybe even make a module that converts any Express-like middlewares into Restify middlewares?

This is a really interesting idea, very well may be possible but I'd have to dig more into what the common patterns in express plugins are.

> I'd have to look into Restify, but there could be some more differences that may complicate really having two-in-one type of deal as well

I'd be happy to invest in closing these deltas. Ideally the two communities could share plugins, the core of restify/express are similar but have subtly different goals. The more we can reconcile, the more we can share between the projects.

**Comment by retrohacker** [comment]
I'll start digging into a `restify-ify` module that converts express middleware into restify compatible middleware.

**Comment by retrohacker** [comment]
We don't do `originalUrl` but looking into how that can be done.

**Comment by dougwilson** [comment]
Hi @retrohacker sorry this fell off my plate here. So where did we land here, in the end? I know you were going to look into how to make an adapter, but no sure if you had the chance yet, or you have some feedback on how that went for something we can incorporate here.

**Comment by dougwilson** [comment]
This issue is quite old at this point, and Restify may have changed in that time (I'm not sure, though). But I do think Restify support is liekly outside the scope of this module. I would suggest either take the guts of this middleware to make something for Restify, or if Restify supports an Express middleware compatibility layer, you should be able to use an Express middleware like this using that.
