### ISSUE TITLE
Wrong data responsed with large file (>4GB)

### ISSUE THREAD

**Issue by gt945** [expressjs/serve-static#111]
request file with range 4294967296- , the return data is wrong.
```
curl -v -X GET -H "range: bytes=4294967296-"  http://url/to/path
```
This bug occurs with large files that > 4GB,  and only data after 4GB is wrong

**Comment by dougwilson** [comment]
What version of Node.js are you using? Early versions of Node.js 10 have the bug you are describing so I would like to rule that out.

**Comment by gt945** [comment]
10.0.0
Thanks a lot, your information is very helpful.
I update to 10.6.0 and problem fixed.

**Comment by dougwilson** [comment]
No problem!
