### ISSUE TITLE
How to serve a specific public folder depending on the sub domain vhost

### ISSUE THREAD

**Issue by KayHS** [expressjs/serve-static#115]
Hi,

Ive asked this question on stackoverflow and unfortunately no one has given me an answer.  So i hope you don't mind me asking here.

> I want to serve a public folder with the same name as the subdomain.

Depending on the vhost (*.localhost.com) i want to serve a specific public app. For example

`app1.localhost.com` would serve `/public/app1/index.html`

**etc/hosts** 

```
127.0.0.1   localhost
127.0.0.1   app1.localhost
```

**routes.js**
```
        this.app = express();
        this.config = new Config();

        this.static = connect();

        this.app.use(vhost("*.localhost", (req, res, next) => {
            const host = req.vhost[0];
            const hostPath = path.join(__dirname, "public", host);
            this.static.use(serveStatic(hostPath));
            next();
        }));

        this.app.use("/api/v1/core", CoreRouter);

```

This just . gives me 

> Cannot GET /

**Comment by dougwilson** [comment]
You're very close, but I would use URL rewriting to achieve the result myself. Example:
```js
        this.app = express();
        this.config = new Config();

        this.static = express.Router();
        this.static.use((req, res, next => {
            const subhost = req.vhost[0];
            req.url = `/${subhost}${req.url}`;
            next();
        });
        this.static.use(serveStatic(path.join(__dirname, 'public')));

        this.app.use("/api/v1/core", CoreRouter);

        this.app.use(vhost("*.localhost", this.static));
```

**Comment by KayHS** [comment]
I tried to following the examples in the readme here - https://www.npmjs.com/package/vhost

This still gives me `Cannot GET /`.  The subhost is giving me app1 which is correct. 

The only thing i can think of is that im bundling my es6 app into `/dist/index.js` however im also outputing a `/dist/public/app1`. So there should be no problem.

**Comment by dougwilson** [comment]
Hm. Is it possible you can provide a complete app that I can run and test against? Not sure what all the variables are in your example.

**Comment by KayHS** [comment]
Yes i can provide it privately, if you're able to give me an email

**Comment by dougwilson** [comment]
I don't need your private app, just _an_ app that is complete that represents the issue. Moving it around privately won't help future users who have the same issue. For example, you were looking for help and found nothing, maybe because everyone is trading source privately.

**Comment by KayHS** [comment]
Theres no single .js file i can give you, so this is going to be tricky.

**Comment by dougwilson** [comment]
Alright. Let me write a self-contained app that works (kind of like the examples in the README) and then you should be able to translate over into the structure of your app 👍

**Comment by KayHS** [comment]
i think the code you have provided is quite self contained. 

However, i would appreciate that.

**Comment by KayHS** [comment]
Then this suggests it has something to do with the setup of my app specifically. I am bundling using webpack, this shouldint cause an issue to find the public directory?

```
const path = require("path");
const WebpackShellPlugin = require("webpack-shell-plugin");
const nodeExternals = require("webpack-node-externals");
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {

    mode: "development",
    entry: "./src/index.js",
    target: "node",
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
    devtool: "source-map",
    
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "index.js",
        sourceMapFilename: "index.js.map"
    },
    module: {
        rules: [
            {
                enforce: "pre",
                test: /\.js$/,
                exclude: /node_modules/,
                loader: "eslint-loader",
            },
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["@babel/preset-env"]
                    }
                }
            }
        ],
    },
    "plugins": [
        new WebpackShellPlugin({ onBuildStart: [], onBuildEnd: ["nodemon dist/index.js"] }),
        new CopyWebpackPlugin([
            { from: 'src/public/', to: 'public/' }
        ]),
    ]

};
```

**Comment by dougwilson** [comment]
I've never used webpack, so not sure. The above doesn't of course really mean anything to myself who lacks the webpack knowledge:)

**Comment by dougwilson** [comment]
So I'm going to close this, as I don't think there is anything further I can provide here. Let me know if I closed prematurely.
