### ISSUE TITLE
maxAge can't set Cache-Control header

### ISSUE THREAD

**Issue by bali2016** [expressjs/serve-static#116]
I use express to server static files with those code:

`app.use(serveStatic(path.join(__dirname, 'public'), {
	maxAge: '500s'
}));`

In the browser, when requesting the static file, the Cache-Control header is not what I want:

> Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
> Connection: keep-alive
> Content-Length: 29881
> Content-Type: image/png
> Date: Tue, 27 Nov 2018 10:30:42 GMT
> ETag: W/"74b9-1674ef9cd58"
> Expires: 0
> Last-Modified: Mon, 26 Nov 2018 07:44:13 GMT
> Pragma: no-cache
> Strict-Transport-Security: max-age=15552000; includeSubDomains
> Surrogate-Control: no-store
> X-Content-Type-Options: nosniff
> X-DNS-Prefetch-Control: off
> X-Download-Options: noopen
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block

And debugging, I found the maxAge function was blocked by some Cache-Control headers that already set:
```
send/index.js: SendStream.prototype.setHeader = function setHeader (path, stat) {
....
  if (this._cacheControl && !res.getHeader('Cache-Control')) {
    var cacheControl = 'public, max-age=' + Math.floor(this._maxage / 1000)

    if (this._immutable) {
      cacheControl += ', immutable'
    }

    debug('cache-control %s', cacheControl)
    res.setHeader('Cache-Control', cacheControl)
  }
```
I found the `res.getHeader('Cache-Control')`  returns the 

> Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate

So the maxAge Cache-Control header was not set.

My questions:

- Which one set the "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate"? I just use the express to serve the static files.

- Can we add a option to over write the Cache-Control headers if there is already Cache-Control header in the response?

Thanks,
Bali

**Comment by bali2016** [comment]
Workaround the issue, I used the following code:
`app.use(serveStatic(path.join(__dirname, 'public'), {
	maxAge: '1d',
    cacheControl: true,
    setHeaders: function (res, path) {
        if (res.getHeader('Cache-Control')) {
        	res.removeHeader('Cache-Control');
        }
    }
}));`

Even though it looks strange, but it works. 

> Accept-Ranges: bytes
> Cache-Control: public, max-age=86400
> Connection: keep-alive
> Date: Tue, 27 Nov 2018 11:10:03 GMT
> ETag: W/"74b9-1674ef9cd58"
> Expires: 0
> Last-Modified: Mon, 26 Nov 2018 07:44:13 GMT
> Pragma: no-cache
> Strict-Transport-Security: max-age=15552000; includeSubDomains
> Surrogate-Control: no-store
> X-Content-Type-Options: nosniff
> X-DNS-Prefetch-Control: off
> X-Download-Options: noopen
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block

**Comment by dougwilson** [comment]
Hello! I'm not sure what is setting that cache-control header before this module in your app, unfortunately. Is it possible you can provide code that reproduces it?

This module does not override any already set header as a feature, as the assumption is that if you have set it, that is the value you want it to be and this module just adds it if has not already been set (i.e. a default).

**Comment by dougwilson** [comment]
Closing due to no response.
