### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by jaison10** [expressjs/serve-static#118]
I have given this code in my js file
```app.use("/",express.static(__dirname + '/static'));```
where static is a folder containing html and css file that I want to display.
But on running ```localhost:1337``` it says ```Cannot GET /```

I'm using windows10.
Is that error because the OS is Windows?

Help me to solve please!

Thank you,
JAISON

**Comment by dougwilson** [comment]
Hello! What files are in your static directory? Do you have a index.html file?

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by efstathiosntonas** [comment]
You could try this:
```
  app.use("/images", serveStatic(path.join(`${__dirname}/images`), {
    maxAge: '1d',
  }))

```

**Comment by kuanyui** [comment]
I encountered the same issue:

```js
var contentDisposition = require('content-disposition')
var finalhandler = require('finalhandler')
var http = require('http')
var serveStatic = require('serve-static')
var path = require('path')
var os = require('os')

const ROOT = path.join(process.env.HOME, 'tmp')
console.log(ROOT)
var serve = serveStatic(ROOT, {
  'index': false,
  'setHeaders': setHeaders
})

// Set header to force download
function setHeaders (res, path) {
  res.setHeader('Content-Disposition', contentDisposition(path, {type: 'inline'}))
}

// Create server
var server = http.createServer(function onRequest (req, res) {
  serve(req, res, finalhandler(req, res))
})

// Listen
server.listen(8000)
```

And it always returns `Cannot GET /`.

OS is Manjaro Linux.
`~/tmp` has lots of directories and files of various extensions.
