### ISSUE TITLE
Precondition failed error without using datejs

### ISSUE THREAD

**Issue by Dhananjay08** [expressjs/serve-static#119]
PreconditionFailedError: Precondition Failed
    at SendStream.error (/web/servers/chatserver/server/node_modules/send/index.js:270:31)
    at SendStream.send (/web/servers/chatserver/server/node_modules/send/index.js:633:12)
    at onstat (/t7pg/web/servers/chatserver/server/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by dougwilson** [comment]
Hi! Thanks for the report. Typically this is a client error. Are you sure the client did not include a precondition in that request that failed? If not, is it possible you can provide us a test case we can reproduce the issue?

**Comment by Dhananjay08** [comment]
we have included the precondition failure

**Comment by dougwilson** [comment]
Gotcha. So if the request includes a precondition that fail, it is expected to error.

**Comment by Dhananjay08** [comment]
This is not happening at my side. This is client issue. can u explain why this issue is happening

**Comment by dougwilson** [comment]
If the client sends a request with a precondition that fails, the error will be dent back to the client.

**Comment by Dhananjay08** [comment]
The requests involves which type and when?

**Comment by dougwilson** [comment]
I'm not sure what specific request would cause that in your app, especially as this module is not even in the stack trace provided.

Here is some general information about that error if it helps: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412

**Comment by Dhananjay08** [comment]
These are from "send" module
