### ISSUE TITLE
Redirect does not include hostname

### ISSUE THREAD

**Issue by rishabhkohli** [expressjs/serve-static#121]
I have a public folder which contains subfolders to serve from.
```
app.use(express.static("public")
```
With this, if I request for `http://localhost:4000/live`
It is redirected to `http://localhost:4000/live/`

But when I put the express app behind an apache reverse proxy which maps `http://example.com/nodejs` to the internal server at `http://localhost:4000`, my request to `http://example.com/nodejs/live` gets redirected to `http://example.com/live/`

This is because when the redirect option is enabled, it sends back the location header as `/live/`
Apache should rewrite this to `http://example.com/nodejs/live/` but it only catches and rewrites it if the header contains the full host name `http://localhost:4000/live/`

Should express not be sending the location headers without the starting slash `live/` or with a period `./live/` or with the full host name `http://localhost:4000/live/`?

**Comment by dougwilson** [comment]
Behind a reverse proxy where the URL is being rewritten, set the [`req.originalUrl`](http://expressjs.com/en/4x/api.html#req.originalUrl) to the original URL before the rewrite so redirects (like this module) can calculate the URL. Alternatively the reverse proxy can also rewrite the `Location` header response header to correct for it's rewrite.

**Comment by dougwilson** [comment]
You can also disable the redirect feature with `{redirect: false}` is that is desirable for your use-case as well 👍

**Comment by rishabhkohli** [comment]
> Behind a reverse proxy where the URL is being rewritten, set the [`req.originalUrl`](http://expressjs.com/en/4x/api.html#req.originalUrl) to the original URL before the rewrite so redirects (like this module) can calculate the URL. Alternatively the reverse proxy can also rewrite the `Location` header response header to correct for it's rewrite.

If I do that, I have to code the express app to be specific to this server configuration. Ideally, the express app does not need to know that it is running at `http://example.com/nodejs`.



> You can also disable the redirect feature with `{redirect: false}` is that is desirable for your use-case as well 👍

This is what I have currently done to fix this. But now I have had to add a route for every subfolder I have in the public folder.
```
app.get("/live", (req, res, next) => {
	res.redirect("./live/")
})
```

**Comment by dougwilson** [comment]
The express server does not need to be coded specifically. Either the reverse proxy can rewrite the response location header or it should add the original url as a request header and that is the value your app sets req.originalUrl to.

**Comment by rishabhkohli** [comment]
That's a neat idea.
Thanks. I will try that.
