### ISSUE TITLE
Incorrect cloning options with Object.create

### ISSUE THREAD

**Issue by Ntropy** [expressjs/serve-static#139]
Incorrect cloning with using Object.create
https://github.com/expressjs/serve-static/blob/master/index.js#L48
Object.assign should be used instead

**Comment by dougwilson** [comment]
It is not intended to clone the options, which is why `Object.create` is used instead of `Object.assign`.

**Comment by Ntropy** [comment]
> It is not intended to clone the options, which is why `Object.create` is used instead of `Object.assign`.

So, how to define options for serv static?
if operation Object.create just erase them all
For example: const opts = Object.create({index: 'index.html'}); // opts === {}

**Comment by dougwilson** [comment]
Just follow the the examples in the readme, it should all be there. You can also check out the tests in our test suite. Just pass in an object for the options argument.

The reason you are seeing {} is just how your web browser is rendering the object's keys incorrectly.
