### ISSUE TITLE
Unable to install serve-static 1.14.2 from npm

### ISSUE THREAD

**Issue by schematis** [expressjs/serve-static#144]
I'm not sure if this is an issue that can be resolved on your end, but while the version is listed on the npm site, `npm install serve-static` installs 1.14.1 and throws an error when trying to find 1.14.2.

**Comment by dougwilson** [comment]
Unfortunately this is unlikely something I can fix. Almost always when someone reports this type of issue, they have their configured registry to something that is not the real npm registry, so I would check that first. Otherwise it may be a momentary issue with the npm registry.

**Comment by dougwilson** [comment]
You can check the registry you are using with the command `npm config get registry`

**Comment by schmitch** [comment]
btw. we have the same problem and we are using nexus repository manager, looks like it's a bug there?
I mean the version is inside the cache, but npm still returns an error.

i.e. `curl` works but npm soomehow fails. it's really wierd. maybe also a combination of nexus and npm > 8, no idea. just fyi

**Comment by schematis** [comment]
Yep. We're using Nexus as well; I'll check into that and see what's going on. The weird bit is that yarn pulls the correct package.
