### ISSUE TITLE
Question: Is it possible to access the origin from setHeaders()?

### ISSUE THREAD

**Issue by elcferreira** [expressjs/serve-static#145]
Hallo,

I'm having a problem to setup multiples domain to be `Access-Control-Allow-Origin`.
I don't like to use `*` because of security issues, so I was trying to apply this solution bellow:

https://stackoverflow.com/questions/24897801/enable-access-control-allow-origin-for-multiple-domains-in-node-js

Is it possible to access the `origin` on the parameters returned on `setHeaders`?

`setHeaders(res, path, stat) {}`

Thank you for all help. ❤️

**Comment by elcferreira** [comment]
Solution:

I'm using nuxt, and I tried to do it on

`render > setHeaders`,

But i switch the logic to `serverMiddleware` and it works.

😄

**Comment by dougwilson** [comment]
Hi @elcferreira hm.. I'm not sure exactly what nuxt.js is, as I haven't used it before. This particular module is an Express.js middleware. In Express.js, there is the `res.req`: https://expressjs.com/en/4x/api.html#res.req
