### ISSUE TITLE
Use seconds instead of milliseconds for maxAge

### ISSUE THREAD

**Issue by naz** [expressjs/serve-static#150]
The `max-age` value in `cache-control` is supposed to be passed in in seconds ([max-age spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives).) The middleware [accepts milliseconds](https://github.com/expressjs/serve-static/blob/a39a0df51aa31f22b4947ade34fd90b14c7be1ea/README.md#maxage) for maxAge paramter, which creates a bit of confusion around conversion from one unit to another. 

As a reference where seconds are used for max-age - the [CORS middleware passes along seconds](https://github.com/expressjs/cors/blob/f038e7722838fd83935674aa8c5bf452766741fb/lib/index.js#L134-L141) instead of milliseconds.

Not sure what's the best way to disambiguate the situation and start using seconds. Maybe allowing to pass in an additional property "seconds: true" to the middleware could be one of the approaches. Not sure. Just found this behavior confusing and have cought some major bugs that in the codebase that were coming out of the second/millisecond confusion.

**Comment by dougwilson** [comment]
Yea,I certainly agree with you, but it's going to be very difficult as even if it's changed with a major version bump all the example and videos out there will still work and people will end up even more confused. We already tried once. The best thing to do to disambiguare is to use a string instead: `'40s'` for 40 seconds.
