### ISSUE TITLE
error TS2688: Cannot find type definition file for 'mime'.

### ISSUE THREAD

**Issue by porameht** [expressjs/serve-static#162]
I keep getting this error on "npm run build"

![Screenshot 2567-04-01 at 11 17 17](https://github.com/expressjs/serve-static/assets/89307294/2f9da5f2-ac3b-4987-ae94-2b7d86fcecab)

Node version : 16

![Screenshot 2567-04-01 at 11 17 10](https://github.com/expressjs/serve-static/assets/89307294/8326eb40-235b-46b1-8201-c9828ad2934a)

How can I resolve this conflict and ensure I have the correct type definitions for the versions of 'mime' being used?
Is there a specific way to manage multiple versions of 'mime' and their type definitions?

**Comment by the-1aw** [comment]
Not sure what happened but it looks like mime's type definitions were deprecated through 4.0.0

In case it can help, I ended up using package.json resolution as a workaround.
```
"resolutions": {
    "@types/mime": "^3 || ^1"
},
```

**Comment by jonchurch** [comment]
Just ran into this at work and remembered seeing this issue. 

It appears that `@types/mime@4.0.0` is deprecated now. I dont know why yet, the message on NPM says that mime ships it's own types now.

I'll keep this open for now bc folks will likely come looking, but there isn't anything we can do over here, it's an upstream issue.

**Comment by jonchurch** [comment]
This should be resolved with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69231

Closing, let me know if something goes awry.
