### ISSUE TITLE
maxAge doesn't work

### ISSUE THREAD

**Issue by Mirodil** [expressjs/serve-static#31]
here is configuration:
case 1:
```js
app.use(express.static(path.join(__dirname, 'public'), { maxAge: '1d' }));
```
response header
```
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Date: Thu, 26 Feb 2015 07:42:43 GMT
Cache-Control: public, max-age=0
Last-Modified: Tue, 27 Jan 2015 14:10:51 GMT
Content-Type: text/css; charset=UTF-8
Content-Length: 110630
Connection: keep-alive
```

**Comment by gfaceless** [comment]
make sure update your express and serve-static to the latest version.
`ms` support may not be there in previous ones.

**Comment by dougwilson** [comment]
@Mirodil you need to use at least version 1.3.0 of this module to use strings for `maxAge`. If you are using an older version, always feel free to reference the exact `README.md` file that's in your `node_modules` folder to know what arguments and types are accepted on your installed version :)
