### ISSUE TITLE
Files not being fully sent

### ISSUE THREAD

**Issue by ilanbiala** [expressjs/serve-static#34]
I have static files in a directory `public/` that are being loaded on my website. However, the file is only partially loaded because I have x lines and it loads 70 or 90 or some portion of the file. I checked that the file is truly x lines by `cat`'ing it...so I'm not sure what's going on exactly. I'm using serve-static directly after thinking that Express might not have the most up-to-date version. Any thoughts?

**Comment by dougwilson** [comment]
I don't have any off-hand thoughts, no. My only thoughts currently is just something else you have loaded that is interfering with the responses. There hasn't been any changes related to content cut-offs, so I don't think upgrading will end up with any results.

Two things you can try:

1. Start by turning off any middleware above the static one one-by-one to see if disabling one fixes the issue.
2. If you an distill down a way to reproduce and post it here, that would be awesome!

**Comment by ilanbiala** [comment]
@dougwilson I disabled all middleware before my static middleware. Morgan logs `GET /app.min.js 200 22.308 ms - 374950`, but then the request in the Network tab says `net::ERR_CONTENT_LENGTH_MISMATCH`.

**Comment by dougwilson** [comment]
Morgan just logs the `Content-Length` header, so they would, of course, match :) Can you verify if that's the number of bytes in the file? Otherwise, I'm not really sure; you can always try starting with `DEBUG=send` and seeing if there is any useful output, otherwise it would be nice to be able to reproduce and I can pinpoint the issue down ASAP.

**Comment by ilanbiala** [comment]
The number of bytes based on `wc -c < public/app.min.js` is indeed 374950. I'm basing that off of http://stackoverflow.com/questions/1815329/portable-way-to-get-file-size-in-bytes-in-shell.

**Comment by dougwilson** [comment]
Ok. I would try to make absolutely sure there is no proxy between you and the server as well, even trying to run this on a different machine, if possible. The fact that the file matches makes sense, because `Content-Length` is just from the file's stat, so that's a good value there.

**Comment by ilanbiala** [comment]
When I set `DEBUG=send` I see some of the other requests are getting some things like etag, pipe, modified, content-type, but the specific request that has this issue has no other statements printed out other than Morgan's.

**Comment by dougwilson** [comment]
Try to only request that single file so your logs are readable. i.e. you can just enter the URL in your browser to use something like cURL.

**Comment by ilanbiala** [comment]
My nginx config file for this site is:
```
upstream serverName {
	server 127.0.0.1:3000;
}

server {
	listen 80;
	root /var/www/website.com;
	server_name www.website.com website.com;

	location / {
		proxy_pass http://serverName;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Conneciton 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}
}
```
There's nothing suspicious there, right?

**Comment by dougwilson** [comment]
> There's nothing suspicious there, right?

I don't think so, but I can also say I'm not familiar enough with nginx to say with any certainty :)

**Comment by dougwilson** [comment]
I did not actually read this, but did a quick Google. Perhaps it has something useful.

http://stackoverflow.com/questions/25993826/err-content-length-mismatch-on-nginx-and-proxy-on-chrome-when-loading-large-file

**Comment by ilanbiala** [comment]
@dougwilson it turns out that there wasn't enough space on my server for Nginx to buffer the whole file, so I restarted my server and now it seems to be working again. Thanks for helping to narrow it down, I would never have though of the issue being lack of free space on the server!

**Comment by dougwilson** [comment]
Oh, nice! I'm glad the issue has been resolved :)

**Comment by NileshWangad** [comment]
@ilanbiala Thank you. It's working great!!!!!
