### ISSUE TITLE
Incorrect content type

### ISSUE THREAD

**Issue by dwest-ee** [expressjs/serve-static#37]
Hi,

I'm using Node 0.12.2 with serve-static 1.9.2, and the content type for static files is incorrect. For example JS files are being sent with the response header content type of 'text/html'.

**Comment by dougwilson** [comment]
Hi! For some reason I'm not able to reproduce. I would start with assuming you have a corrupted install of node modules on your disk. I suggest wiping all your node modules and re-installing to see if that fixes the issue. The procedure to do this is:
```sh
# Delete your install of this module fully
rm -rf node_modules/serve-static
# Delete your local npm cache (which is what usually gets corrupted)
npm cache clean
# Install this module again
npm install serve-static
```

If it's still not working after doing that, please see if you can investigate it and see what you can find. One thing to try is to set the environment variable `DEBUG` to `send` (so `DEBUG=send`) and then run your server and request a static file. Then just paste that debug output here.

**Comment by dougwilson** [comment]
Hi @dwest-ee have you tried anything yet or collected that information for me?

**Comment by dwest-ee** [comment]
Hi @dougwilson, thank you for your quick response and direction. Must have been the cache as removal of the installed modules made no difference, however npm cache clean did the trick.

**Comment by dougwilson** [comment]
Ah. Yea, I'm not sure why this happens some times. It seems to happen with various modules I have using `node-mime` (which does the content-type lookup), where the install gets corrupted somehow in the npm cache.
