### ISSUE TITLE
Servestatic only serves partly a directory

### ISSUE THREAD

**Issue by jenyckee** [expressjs/serve-static#41]
I have a node.js server
```javascript
var connect = require('connect'),
    http = require('http'),
    serveStatic = require('serve-static'),
    path = require('path'),
    app = connect().use(serveStatic(path.resolve(__dirname,'../app'))).listen(3000);
```
The app folder contains my bower_components folder with about 90 subfolders of bower components installed. When I try to serve this only part of these get served and when I refresh the browser the amount of components served vary. This is not desirable. What could be the problem?

https://github.com/jenyckee/polymer-socketio

**Comment by dougwilson** [comment]
Hm, I've never heard of this issue before. Can you provide more information on how I could potentially reproduce this?

One thing you can try is launching your server with `DEBUG=send` in the environment and seeing what debugging `send` is printing (like what the file names that are being stat'd, etc.) to see if that helps you diagnose.

**Comment by jenyckee** [comment]
The issue occurs with the project in the repository I included.

https://github.com/jenyckee/polymer-socketio

**Comment by dougwilson** [comment]
Sure, and I can look at that, but that may not happen for a few weeks. If you could reduce the test case to something very simply I could easily copy and paste, or even just a PR here with a failing test, that would help a lot, otherwise there's a lot of work for me, so you'd have to wait much longer. I don't even know if that works on Windows, and what version of Node.js you are using, if running on Windows would even reproduce, or how to use that repo to reproduce at all, since there's no instructions for how to reproduce using that repo.

**Comment by dougwilson** [comment]
@jenyckee what are the steps I need to do with https://github.com/jenyckee/polymer-socketio to see the issue?

**Comment by jenyckee** [comment]
npm install && bower install && gulp serve

**Comment by dougwilson** [comment]
Will gulp serve throw an error or do I have to do something after that?

**Comment by jenyckee** [comment]
No, no errors, you'll see however in your browser that not the entire file structure is served as expected. I'm using Mac osx 10.9.5 with chrome 43.0.2357.124

**Comment by jenyckee** [comment]
Could it be that only the files are served that are referenced too directly in index.html? The files are referenced indirectly through html imports (in the elements.html file).

**Comment by dougwilson** [comment]
All this module is serve files your browser asks for. Do you see the network requests for those files?

**Comment by jenyckee** [comment]
Yes, returning a 404 response

**Comment by dougwilson** [comment]
Gotcha, so that means that the network request was made. Any news on collecting the information from the  DEBUG=send  tip above?

**Comment by jenyckee** [comment]
I have no experience on how to interpret the output but this is what I get

send stat "/Users/jenyckee/disco-web/app/index.html" +0ms
  send pipe "/Users/jenyckee/disco-web/app/index.html" +3ms
  send modified Thu, 25 Jun 2015 15:27:57 GMT +2ms
  send etag W/"2f1-14e2b552448" +0ms
  send content-type text/html +0ms
  send stat "/Users/jenyckee/disco-web/app/index.html" +7s
  send pipe "/Users/jenyckee/disco-web/app/index.html" +1ms
  send modified Thu, 25 Jun 2015 15:27:57 GMT +0ms
  send etag W/"2f1-14e2b552448" +0ms
  send content-type text/html +1ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/styles/main.css" +70ms
  send pipe "/Users/jenyckee/disco-web/app/styles/main.css" +2ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"26e-14e24ba2d90" +0ms
  send content-type text/css +0ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/webcomponentsjs/webcomponents-lite.js" +1ms
  send stat "/Users/jenyckee/disco-web/app/scripts/app.js" +5ms
  send stat "/Users/jenyckee/disco-web/app/scripts/teoria.min.js" +4ms
  send pipe "/Users/jenyckee/disco-web/app/scripts/app.js" +1ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"5f3-14e24ba2d90" +0ms
  send content-type application/javascript +0ms
  send not modified +0ms
  send pipe "/Users/jenyckee/disco-web/app/scripts/teoria.min.js" +0ms
  send modified Sun, 19 Apr 2015 19:49:35 GMT +1ms
  send etag W/"3ab5-14cd33a9898" +0ms
  send content-type application/javascript +0ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/elements/elements.html" +16ms
  send pipe "/Users/jenyckee/disco-web/app/elements/elements.html" +1ms
  send modified Thu, 25 Jun 2015 16:18:37 GMT +0ms
  send etag W/"865-14e2b838748" +0ms
  send content-type text/html +0ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/iron-flex-layout/classes/iron-flex-layout.html" +43ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/iron-icons/iron-icons.html" +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/iron-pages/iron-pages.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/iron-selector/iron-selector.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-drawer-panel/paper-drawer-panel.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-header-panel/paper-header-panel.html" +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-icon-button/paper-icon-button.html" +11ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-item/paper-item.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-material/paper-material.html" +2ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-menu/paper-menu.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-styles/paper-styles-classes.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-toast/paper-toast.html" +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/paper-toolbar/paper-toolbar.html" +6ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/platinum-sw/platinum-sw-cache.html" +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/platinum-sw/platinum-sw-register.html" +0ms
  send stat "/Users/jenyckee/disco-web/app/styles/app-theme.html" +1ms
  send pipe "/Users/jenyckee/disco-web/app/styles/app-theme.html" +1ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"171e-14e24ba2d90" +0ms
  send content-type text/html +0ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/elements/my-greeting/my-greeting.html" +16ms
  send stat "/Users/jenyckee/disco-web/app/elements/my-list/my-list.html" +1ms
  send stat "/Users/jenyckee/disco-web/app/elements/routing.html" +0ms
  send pipe "/Users/jenyckee/disco-web/app/elements/my-greeting/my-greeting.html" +0ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"4ea-14e24ba2d90" +0ms
  send content-type text/html +0ms
  send not modified +1ms
  send pipe "/Users/jenyckee/disco-web/app/elements/my-list/my-list.html" +0ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"54e-14e24ba2d90" +0ms
  send content-type text/html +0ms
  send not modified +0ms
  send pipe "/Users/jenyckee/disco-web/app/elements/routing.html" +0ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +0ms
  send etag W/"4bd-14e24ba2d90" +0ms
  send content-type text/html +0ms
  send not modified +0ms
  send stat "/Users/jenyckee/disco-web/app/bower_components/page/page.js" +71ms
  send stat "/Users/jenyckee/disco-web/app/sw-import.js" +1s
  send pipe "/Users/jenyckee/disco-web/app/sw-import.js" +0ms
  send modified Wed, 24 Jun 2015 08:40:58 GMT +1ms
  send etag W/"237-14e24ba2d90" +0ms
  send content-type application/javascript +0ms
  send not modified +0ms

**Comment by dougwilson** [comment]
I interpret it as it saying that, for example, it tried to look up the file `/Users/jenyckee/disco-web/app/bower_components/iron-icons/iron-icons.html` but it doesn't exist on your disk, thus 404. Is that one of your failing files? Does it exist at that location on your disk?

For example, what is the outcome of this command on your machine?
```
$ node -pe 'require("fs").statSync("/Users/jenyckee/disco-web/app/bower_components/iron-icons/iron-icons.html")'
```

**Comment by dougwilson** [comment]
Hi @jenyckee I haven't heard back on my questions above for 6 days and I still don't have clear instructions on how to use your repo. All you provided recently was "[...] you'll see however in your browser that not the entire file structure is served as expected." but that is not helpful to me because I have no idea what to expect, as you have to provided that information.

I'm going to close this for now, but let me know if you can provide full, complete, and clear steps for me to reproduce, otherwise we may just have to wait for someone else to have the issue and provide more details, or perhaps you can even help by issuing a PR here to fix :) I have played around a whole bunch and it always serves files that exist on disk without any issues.
