### ISSUE TITLE
Error: Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by pibu** [expressjs/serve-static#42]
hello, I note the error message Error: Requested Range Not Satisfiable
when I fetch files from mp4 nexus 5 with chrome
sorry but I have my first experience with node
thanks

**Comment by dougwilson** [comment]
Hi @pibu ! Are you then not able to fetch the files or do they still download fine? Seeing `Error: Requested Range Not Satisfiable` is a normal thing that is part of web browser download negotiation.

**Comment by pibu** [comment]
Hi dougwilson 
thank you for your question
the download is successful
but while on windows phone takes about 1 second
ipad mini and takes about the same time
without any warning to the console of node
with Nexus 5 with chrome it takes about 30 seconds with error messages

I'm sorry but this is the first time I work with node
maybe I'm doing something wrong

**Comment by dougwilson** [comment]
As far as your description, I don't see you doing anything wrong. Differences in time, especially if you are using wireless, is hard to pinpoint to anything specific. Also, the error is a normal thing that is part of web browser download negotiation. Not all browser negotiate the same, which is why some browsers you see that and not others.

**Comment by pibu** [comment]
Thank you very much for the answer
excuse me as I said I have no experience
but 30 seconds of difference seemed to me really a lot
whereas are in wifi

**Comment by dougwilson** [comment]
Yes, 30 seconds seems like a lot, but without a way for me to reproduce, it's hard for me to explain anything about why that would be or even if it's related to this module at all.

**Comment by pibu** [comment]
I understand that not having a nexus 5 can not see what I see and reproduce the problem
these days trying to figure out the problem I came across arguments type header
Accept-Ranges example what do you think?
You can make me a little example of how to configure the static content?
at this time use:
app.use (express.static (dirname + __ "/../Player/"));

you have been very kind to answer
thank you very much

**Comment by pibu** [comment]
app.use(express.static(__dirname + "/../Player/"));

**Comment by dougwilson** [comment]
I'm sorry, unfortunately I really have no idea what you are saying in https://github.com/expressjs/serve-static/issues/42#issuecomment-118098470 :( Can you try explaining again with different words, maybe?
