### ISSUE TITLE
ctrl+F5 disables maxAge (cache) in Google Chrome

### ISSUE THREAD

**Issue by Burnett01** [expressjs/serve-static#43]
Whenever I press **CTRL+F5** in Chrome the cache/maxAge configuration won't work anymore. I'm always getting a 200 status-code upon the coming requests, where it should be 304.

Any ideas how to fix this? Thank you very much!

**Comment by dougwilson** [comment]
Hi! I'm not sure what exactly you mean, especially since the whole point of adding Ctrl to the F5 is literally to ignore all caching.

**Comment by Burnett01** [comment]
Alright I didn't know that. Thanks man

**Comment by dougwilson** [comment]
No problem :+1:
