### ISSUE TITLE
question: how does express.static know to default to "index.html" when requesting "/"?

### ISSUE THREAD

**Issue by bcherny** [expressjs/serve-static#45]
i don't see it in the code anywhere.

**Comment by dougwilson** [comment]
Hi! You can find it located in our dependency: `send` at https://github.com/pillarjs/send/blob/0.13.0/index.js#L646-L674

**Comment by bcherny** [comment]
i didn't think of looking in send! thanks for the quick response!

**Comment by dougwilson** [comment]
No problem!
