### ISSUE TITLE
Incompatibility in returned errors between 1.9.3 and 1.10.0

### ISSUE THREAD

**Issue by stefanstoyanov** [expressjs/serve-static#49]
Before the update of the 'send' module the code pasted below returned the error (next(err)), but now it doesn't. With the old version of 'send' the 'err' object had no 'statusCode' property => so !(err.statusCode < 500) returned true. With the new version of 'send' err.statusCode returns some http code (for example 403) and  !(err.statusCode < 500) is false.

 // forward errors
    stream.on('error', function error(err) {
      if (forwardError || !(err.statusCode < 500)) {
        next(err)
        return
      }

      next()
    })

**Comment by dougwilson** [comment]
Hi! I'm sorry, I don't completely understand the report. Can you provide a test case? Perhaps even a PR where you add a test that fails before your change and succeeds after your change"

**Comment by stefanstoyanov** [comment]
Hi, I didn't notice the new 'fallthrough' property. It works fine when I set it to 'false'.
