### ISSUE TITLE
Should fallthrough expose the full ENOENT error and expose the full path?

### ISSUE THREAD

**Issue by ronkorving** [expressjs/serve-static#50]
Right now, when using `fallthrough: true` the ENOENT error is returned as the body of the 404 response, and the entire path on disk is exposed to the client. That seems a bit overkill and exposes more than I would like it to. Can this be addressed or are there good reasons why this is the way it is?

**Comment by dougwilson** [comment]
It is up to your application not to write unlink error messages from the client. The errors provided are simply from Node.js core and are useful for server-side logging.

If you can provide a full app that reproduces, I can help determine how you are writing this to the response.

If it's just default Express logic, putting your app into production mode should help:

    app.set('env', 'production')

**Comment by ronkorving** [comment]
You're right, this is in express, and in production mode the error is not as verbose. Thanks!
