### ISSUE TITLE
static file rewrite?

### ISSUE THREAD

**Issue by AubreyHewes** [expressjs/serve-static#55]
i.e. due to proxy/seo friendly cache-busting..

Currently I can do the following:

    /file.ext?r=HASH => /file.ext

HASH comes from a cachebusting cache of file mtimes..

I would like to do this:

    /file.HASH.ext => /file.ext

I can fix this via apache/nginx rewrite though now need it within an express app on static files..
More proxy/seo friendly they say... 

Is there any current way to explain this to `serve-static` or would I have to implement/override this myself? 

Thanks, A

**Comment by AubreyHewes** [comment]
solved via custom middleware before static-serve ;-)

**Comment by dougwilson** [comment]
Hi @AubreyHewes , sorry I didn't get a chance to respond before you closed the issue :) I'm glad you figured it out. I would have suggested that solution unless you found a reason that it didn't work for you.

**Comment by akarienta** [comment]
Hi @AubreyHewes, can you post your solution here please?

**Comment by AubreyHewes** [comment]
@akarienta A bit late; though for any future visitors..

```javascript
app.use((req, res, next) => {
  req.url = req.url.replace(/\.cb[a-zA-Z0-9]+\./, '.');
  next();
}, express.static(staticPath));
```
