### ISSUE TITLE
Access to stream events

### ISSUE THREAD

**Issue by rtmcached** [expressjs/serve-static#57]
The underlying SendStream emits some events which are also utilized by serveStatic. Could those by also available on serveStatic? (I mean if those could be defined on serveStatic and passed down to each new stream)

Usage example 
```js
var downloadsServeStatic = serveStatic(path.resolve('./downloads'));
downloadsServeStatic.on('stream', function (stream) {
   // pipe stream
});
downloadsServeStatic.on('error', function (error) {
    // handle error
});
```

Or is something like this possible and I just can't find it?

**Comment by dougwilson** [comment]
Hi! This is currently not possible for a number of reasons, with the main reason being that the events do not provide enough context for your handlers to understand what the request was for to make a decision. For example, the `stream` event won't tell you what type of file or the path, so you cannot make conditional logic on that.

The events are a low-level API you can get simply by using the `send` module yourself, which is what I would recommend. The `error` event in your example is exposed as the first argument in the callback already.

Perhaps there is a better solution to do what you are trying to achieve without exposing the events. Can you describe what your goal is?

**Comment by rtmcached** [comment]
Actually I was trying a) to inject data in the response if the file served is a .txt file and b) limit the response stream "speed". 

Yes you are right about event, "b" can be done with events, but "a" not.

Anyway i found express-hijackresponse which is suited for both of my tasks and cooperates greatly with serveStatic.
