### ISSUE TITLE
serve-static looking in incorrect path for file (on Windows 10 anyway)

### ISSUE THREAD

**Issue by xo-chris** [expressjs/serve-static#65]
I am having a weird problem, which I can reproduce using the standard express skeleton project as well as my own project.  I am using the latest version of serve-static and express

If I pass 'public' in as in
app.use(express.static(path.join(__dirname, 'public')));

Then serve-static will append another 'public' to the file path it uses to grab the file.  So if my node project is in C:\MyNodeApp and I request the file http://localhost/public/myImage.jpg then serve-static will look for the file C:\MyNodeApp\public\public\myImage.jpg (not double 'public' in the directory path)

I am using Windows 10 64 bit

My work-around is to create a 'public' folder within my 'public' folder.  

Thanks

Chris

**Comment by dougwilson** [comment]
Hi! Yes, this is how Express `app.use` works. Based on what you are trying to do, have `public` actually be in the URL, you want to use this `app.use` statement instead of what you are using above:
```js
app.use('/public', express.static(path.join(__dirname, 'public')));
```
