### ISSUE TITLE
Serve content of a directory like http-server

### ISSUE THREAD

**Issue by t3m** [expressjs/serve-static#67]
Hi, Sorry to trouble you. I have tried to your sample code many times and without luck. What I want to do, is to serve the content of a directory. So then I can right click and download files, much like http-server but I prefer to do it with your codes. See the codes below. I keep getting "Cannot GET /" when I browse to http://localhost:8000
Any help I would greatly appreciate it. Thanks.
```js
var http = require('http');
var finalhandler = require('finalhandler');
var serveStatic = require('serve-static');
var serve = serveStatic("./");
var server = http.createServer(function(req, res) {
  var done = finalhandler(req, res);
  serve(req, res, done);
});
server.listen(8000);
console.log("listening on 8000");
```

**Comment by dougwilson** [comment]
Hi @t3m! This module only serves the actual file contents. It sounds like in addition to that, you want to get automatically-generated HTML pages showing a listing of a directory. You can do that be using both this module and the `serve-index` module. A good example of combining them can actually be found on the `serve-index` examples: https://github.com/expressjs/serve-index#serve-directory-indexes-with-vanilla-nodejs-http-server

I hope this helps!

**Comment by t3m** [comment]
Douglas, I actually came across that codes previously and it didn't work for me at the time after several attempts. It works now. Sorry for the trouble and thanks so much for your help. I hope you will continue your awesome work in Angular 2. Tom #HappyCoding#
