### ISSUE TITLE
Feature Suggestion: SSL support

### ISSUE THREAD

**Issue by Casuallynoted** [expressjs/serve-static#69]
Hello!

I just wanted to suggest SSL support, it would be awesome to be able to configure serve-static for https.

**Comment by LaKing** [comment]
I think instead of http server, you can simply use https server. You will have to provide key and certificate, and you can even add authentication, this is not part of this module, its a native built-in node feature, so just consult the documentation for node.

**Comment by dougwilson** [comment]
Yes, that is right. You can simply use the vanilla example at https://github.com/expressjs/serve-static#serve-files-with-vanilla-nodejs-http-server and swap the usage of `http` core server with `https` from Node.js core. The interface is the same, except `https.createServer` take an `options` object as the first argument.
