### ISSUE TITLE
Cannot route properly when the path ends with "/" character

### ISSUE THREAD

**Issue by TitaneBoy** [expressjs/serve-static#70]
Hi. I think there is an issue with serve-static. When using it as a middleware function of app.use and when we make a request with the path ending with "/", the request cannot be reached and exectuted properly.

For example:

```
var app = express();
var path = require('path');
app.use("/login", serveStatic(path.join(process.cwd(), '/views/login.html')));
```

When calling 

> http://localhost/login

, all works fine. But when calling 

> "http://localhost/login**/**

 (note the "/" character at the end of the path), it fails saying that we cannot GET /login/.

It only fails when usin serve-static as middleware of app.use. Otherwise, it works fine, even if you put or not the "/" character at the end of the path request.

> **Version used:**
> express: 4.14.0
> serve-static: 1.11.1

Thanks for your help

**Comment by dougwilson** [comment]
Hi @TitaneBoy, this module cannot be used to serve up a single file like in your example. The second argument must be a directory.
