### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by Unforgiven-wanda** [expressjs/serve-static#79]
Hello, 
I am trying to add a 404 page to some of my content.
here is my code: 
```javascript
var connect = require("connect");
var freeport = require('freeport');
freeport(function(err, port) {
  if (err) throw err;
  myport = port;
  var serveStatic = require('serve-static');
	connect().use(serveStatic(`${__dirname}/site`)).listen(port, function(){
	    console.log(`Docs server running on ${myport}...`);
	});
})
```

I try adding an `.htaccess` file and setting `dotfiles` to `allow`, however this module seems to just ignore it. 
Is there some way to accomplish this? To detect a 404 response?

Thank you.

**Comment by dougwilson** [comment]
Hi @Unforgiven-wanda I'm not sure I understand what you're trying to do. This module does not read any instructions from `.htaccess`, which is an Apache-style thing.

**Comment by Unforgiven-wanda** [comment]
Ah yes, a bit of context then.
I am serving a small static website using this module, something like
```
- folder1
- folder2
index.html
someOtherPage.html
```
I would like to have any request that isn't met, be it a 404 error or other to be redirected to a specific page, for example 404.html.

Is there some way to parse the server's response to check the response status' code?

**Comment by dougwilson** [comment]
Ah, I see. So, that would be handling you would need to do in your top-level framework, which looks like is `connect`. A simple example:
```js
var connect = require("connect");
var freeport = require('freeport');
freeport(function(err, port) {
  if (err) throw err;
  myport = port;
  var serveStatic = require('serve-static');
	connect().use(serveStatic(`${__dirname}/site`)).use(send404).listen(port, function(){
	    console.log(`Docs server running on ${myport}...`);
	});
})
function send404(req, res) {
  // send your 404 here
  res.statusCode = 404
  res.end('nothing here!')
}
```

**Comment by Unforgiven-wanda** [comment]
Thank you very much, this was exactly what I was looking for.
Good day.
