### ISSUE TITLE
max-age is always 2592000 for images (.png, .jpg etc.)

### ISSUE THREAD

**Issue by storafrid** [expressjs/serve-static#86]
I've set the `max-age` value to 1 year in my tiny connect server:

```
var connect = require('connect');
var serveStatic = require('serve-static');

connect()
    .use(serveStatic(__dirname, {
        cacheControl: true,
        maxAge: '1 year'
    }))
    .listen(process.env.PORT);
```

This generally works great, giving me `Cache-Control: public, max-age=31536000`. But some resources, such as .png files, are delivered with the value `2592000` instead of `31536000`. Is there something I'm doing wrong?

**Comment by dougwilson** [comment]
Weird. Using the exact code you posed, everything, even .png and .jpg are coming back as  Cache-Control: public, max-age=31536000  for me. Is the above code exactly what you're running to see the issue as well? If you change the max age to like 1 day do the .png and stuff change to be a day, or stay at  2592000 ?

**Comment by storafrid** [comment]
Case closed. I was a victim of my own client cache... disabled cache in Chrome DevTools earlier but somehow the value stuck around a bit. So sorry for stealing your time!
