### ISSUE TITLE
Single file serve?

### ISSUE THREAD

**Issue by iBicha** [expressjs/serve-static#89]
Would a shortcut to `res.sendFile` make sense to be added to serve-static?

i would say

```js
//serving just my index file
router.get('/',  express.static(path.join(__dirname, 'public', 'index.html')));
```

Makes a lot of sense. Any thoughts?

**Comment by dougwilson** [comment]
Hm, yea, that can make sense, especially if it's just a small addition to this module.

**Comment by iBicha** [comment]
Will close for now. Feel free to reopen if still relevent.
