### ISSUE TITLE
How can i change the dir by request header?

### ISSUE THREAD

**Issue by sanguohot** [expressjs/serve-static#98]
I have some static dir to serve,but i have to change my serving when the language changed in the request header 'accept-language:zh-CN,zh;q=0.9'.Any help would be appreciated.

**Comment by dougwilson** [comment]
Hi @sanguohot there are so many different ways to do this, and you didn't provide any specifics, so I can't give you a specific example to help you, but here is a generic example using Express.js:
```js
var express = require('express')
var path = require('path')
var serveStatic = require('serve-static')

var langAssets = {
  'zn': serveStatic(path.join(__dirname, 'public', 'zn')
  'en': serveStatic(path.join(__dirname, 'public', 'en')
  'de': serveStatic(path.join(__dirname, 'public', 'de')
}

var app = express()

app.use(function (req, res, next) {
  var lang = req.acceptsLanguages(Object.keys(langAssets)) || 'en'
  langAssets[lang](req, res, next)
})

app.listen(80)
```

I hope this helps!

**Comment by sanguohot** [comment]
It works for me!Thanks a lot.
