### ISSUE TITLE
Should headers be set depending on mime types?

### ISSUE THREAD

**Issue by mercmobily** [expressjs/serve-static#99]
At the moment I am seeing that `content-type` is not set when serving PNG images. I would assume it would send PNG files as `image/png` . Is serve-static at least supposed to set `content-type`? Or shall I do something to make sure that it happens? If fact, _should_ I make sure the header is set? (My browser will still render those images, although I assume it had to figure out on its own what they were...?)

Thank!

**Comment by dougwilson** [comment]
Yes, this module will always set thr Content-Type header along with various others like Contenr-Length, Last-Modified, ETag, and more. The test suite is validating this happens, but maybe you have some kind of setup we haven't seen. Can you provide all the following so we can diagnose?

1. Version of this module
2. Version of Node.js
3. An example server code that is complete (fully functional if we copy and paste it and run it) that reproduces the issue
4. The file in question and instructions on exactly what to name it and where to place it for your server
5. Thr exact HTTP request to make to your server to see the missing Content-Type header

Thanks!

**Comment by mercmobily** [comment]
Double checking tomorrow. It might well be my fault.

**Comment by mercmobily** [comment]
After much debugging, it turns out that if you do CTRL-R, files come from the cache and content-type doesn't get returned to Chrome (or if it does, Chrome won't show it)

CTRL-SHIFT-R however does a proper reload of images, and they have their content types.

I went insane debugging the whole server-static/send chain (using the wonderful chrome inspect to inspect the code...!) and figured this out myself.

Sorry about the noise. Keep up the good work!
